#!/usr/bin/env python3
"""Build the spec reader's documents payload.

    python3 engine/build-spec-reader-data.py              # write the default output
    python3 engine/build-spec-reader-data.py --out=PATH   # write somewhere else
    python3 engine/build-spec-reader-data.py --cells=PATH # build for a selection

The payload carries the spec text of every version the current publication used,
and the frozen coverage ledger resolved into the shape the reader renders. Both
come from the index tables; there is nowhere else they live.

--cells names a JSON file of the cells a publication is ABOUT to carry. A
publication holds its payloads as columns and is insert-only, so they have to be
built before the row exists; the publish job chooses its cells, points both
builders at them, and inserts the result in one go. Without the flag this builds
for the publication the reader currently serves, which is what the provenance
verifier asks for.

The output is materialised onto the publication row at publication time and
served from there by /api/reader/documents, so this runs when a publication is
made and not on every request.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from coverage_payload import coverage_payload


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "site" / "spec-reader" / "data" / "documents.json"

sys.path.insert(0, str(ROOT / "engine" / "spec-cite"))
import cite  # noqa: E402

# GENERATED by engine/generate_behaviour_constants.py from data/behaviours.json
# (index entries that have a coverage record) -- edit the registry, then
# regenerate; do not hand-edit this block.
def empty_coverage():
    """Coverage record for a document the index has mapped nothing against
    (a user spec). Same keys as coverage_payload(); depth 0 = absent."""
    return {"verdict": None, "depth": 0, "note": "", "verifiedDate": "", "passages": []}


def main(argv=None) -> None:
    out = OUTPUT
    cells = None
    for arg in (sys.argv[1:] if argv is None else argv):
        if arg.startswith("--out="):
            out = Path(arg.split("=", 1)[1])
        elif arg.startswith("--cells="):
            cells = json.loads(Path(arg.split("=", 1)[1]).read_text())
        else:
            raise SystemExit(
                f"unknown argument {arg!r} (supported: --out=PATH --cells=PATH)"
            )

    # The index, out of its tables. There is nowhere else it lives.
    sys.path.insert(0, str(ROOT / "engine"))
    import index_store            # noqa: E402
    from store import Store       # noqa: E402
    store = Store.from_env()
    index_store.install_registry(store)
    records = index_store.coverage(store)
    behaviour_set = index_store.index_behaviours(store)
    bundled = index_store.documents(
        store, index_store.published_spec_version_ids(store, cells=cells))
    user_docs = []
    documents = bundled
    generated_from = ["supabase: aci_spec_versions", "supabase: aci_coverage"]

    behaviours = []
    for behaviour in behaviour_set:
        per_document = {}
        for document in bundled:
            matches = [
                item
                for item in records
                if item["behaviour_id"] == behaviour["id"]
                and item["lab_id"] == document["id"]
            ]
            if len(matches) != 1:
                # Anything but exactly one record per (behaviour, document)
                # fails loudly, naming the behaviour and document.
                raise SystemExit(
                    f"behaviour {behaviour['id']} ({behaviour['slug']}): expected exactly one "
                    f"{document['id']} coverage record, found {len(matches)}"
                )
            per_document[document["id"]] = coverage_payload(
                matches[0], document["id"], behaviour["slug"]
            )
        for document in user_docs:
            per_document[document["id"]] = empty_coverage()
        behaviours.append(behaviour | {"coverage": per_document})

    payload = {
        "generatedFrom": generated_from,
        "behaviours": behaviours,
        "documents": documents,
    }

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(payload, ensure_ascii=False, separators=(",", ":")))
    print(f"Wrote {out.relative_to(ROOT) if out.is_relative_to(ROOT) else out}")


if __name__ == "__main__":
    main()
